"""reinitialize db model

Revision ID: 161fddde3e7e
Revises: 
Create Date: 2026-09-04 18:17:54.771477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161fddde3e7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DB_EDITOR', 'NORMAL', 'NON_AUTH', 'LEADER', 'MEMBER', name='role'), nullable=False),
    sa.Column('group_list', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_uuid'), 'accounts', ['uuid'], unique=False)
    op.create_table('group_account',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('group_role', sa.Enum('ADMIN', 'DB_EDITOR', 'NORMAL', 'NON_AUTH', 'LEADER', 'MEMBER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'account_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leader_list', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('member_list', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_table('results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_results_result_id'), 'results', ['result_id'], unique=False)
    op.create_table('forms',
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('result_id_list', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_index(op.f('ix_forms_form_id'), 'forms', ['form_id'], unique=False)
    op.create_table('pages',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_pages_page_id'), 'pages', ['page_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_type', sa.Enum('OQ', 'CQ', 'SC', 'DT', 'DS', name='questiontype'), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scale_begin', sa.Integer(), nullable=True),
    sa.Column('scale_end', sa.Integer(), nullable=True),
    sa.Column('options', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=False),
    sa.Column('pre_id', sa.String(length=36), nullable=True),
    sa.Column('next_id', sa.String(length=36), nullable=True),
    sa.Column('is_temp', sa.Boolean(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('answers',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pages_page_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_forms_form_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_results_result_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('group_account')
    op.drop_index(op.f('ix_accounts_uuid'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
