"""change PK

Revision ID: 17a49cc1a9e3
Revises: 7268d03fecd7
Create Date: 2026-09-09 15:35:19.739292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a49cc1a9e3'
down_revision: Union[str, None] = '7268d03fecd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("verified_in_progress_pkey", "verified_in_progress", type_="primary")
    op.create_primary_key("verified_in_progress_pkey", "verified_in_progress", ["uuid"])
    op.alter_column("verified_in_progress", "user_id", existing_type=sa.String(length=36), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
