"""add one column in ver

Revision ID: 3542549c702f
Revises: 17a49cc1a9e3
Create Date: 2026-09-09 15:49:30.900661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3542549c702f'
down_revision: Union[str, None] = '17a49cc1a9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verified_in_progress', sa.Column('is_ver', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verified_in_progress', 'is_ver')
    # ### end Alembic commands ###
