"""change group_account PK

Revision ID: 6eaebf9d6b96
Revises: 3542549c702f
Create Date: 2026-09-10 02:05:04.635866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eaebf9d6b96'
down_revision: Union[str, None] = '3542549c702f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("group_account_pkey", "group_account", type_="primary")
    op.create_primary_key("group_account_pkey", "group_account", ["uuid"])
    op.alter_column("group_account", "account_id", new_column_name="user_id")
    op.alter_column("group_account", "group_id", existing_type=sa.String(length=36), nullable=False)
    op.alter_column("group_account", "user_id", existing_type=sa.String(length=36), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
