"""add uuid in verification and group_role

Revision ID: 7268d03fecd7
Revises: bfca9b52a99a
Create Date: 2026-09-09 14:58:00.541338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7268d03fecd7'
down_revision: Union[str, None] = 'bfca9b52a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_account', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('group_account', sa.Column('is_delete', sa.Boolean(), nullable=False))
    op.add_column('group_account', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('group_account', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_group_account_uuid'), 'group_account', ['uuid'], unique=False)
    op.add_column('verified_in_progress', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.drop_index(op.f('ix_verified_in_progress_user_id'), table_name='verified_in_progress')
    op.create_index(op.f('ix_verified_in_progress_uuid'), 'verified_in_progress', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verified_in_progress_uuid'), table_name='verified_in_progress')
    op.create_index(op.f('ix_verified_in_progress_user_id'), 'verified_in_progress', ['user_id'], unique=False)
    op.drop_column('verified_in_progress', 'uuid')
    op.drop_index(op.f('ix_group_account_uuid'), table_name='group_account')
    op.drop_column('group_account', 'update_time')
    op.drop_column('group_account', 'create_time')
    op.drop_column('group_account', 'is_delete')
    op.drop_column('group_account', 'uuid')
    # ### end Alembic commands ###
