"""add reason column in Group

Revision ID: ab026b738580
Revises: 7de4aafc01f6
Create Date: 2026-09-25 23:17:49.105606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab026b738580'
down_revision: Union[str, None] = '7de4aafc01f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forms', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'CLOSED', name='formstatus'),
               type_=sa.String(length=9),
               existing_nullable=False)
    op.add_column('groups', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'reason')
    op.alter_column('forms', 'status',
               existing_type=sa.String(length=9),
               type_=postgresql.ENUM('DRAFT', 'PUBLISHED', 'CLOSED', name='formstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
