"""add verification table

Revision ID: bfca9b52a99a
Revises: 5336c1d5636a
Create Date: 2026-09-09 14:44:26.232635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfca9b52a99a'
down_revision: Union[str, None] = '5336c1d5636a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_in_progress',
    sa.Column('campus_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id_card_link', sa.String(length=255), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_verified_in_progress_user_id'), 'verified_in_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verified_in_progress_user_id'), table_name='verified_in_progress')
    op.drop_table('verified_in_progress')
    # ### end Alembic commands ###
